language: python
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36-django22
      - python: 3.6
        env: TOX_ENV=py36-django30
      - python: 3.6
        env: TOX_ENV=py36-django31
      - python: 3.7
        env: TOX_ENV=py37-django22
      - python: 3.7
        env: TOX_ENV=py37-django30
      - python: 3.7
        env: TOX_ENV=py37-django31
      - python: 3.8
        env: TOX_ENV=py38-django22
      - python: 3.8
        env: TOX_ENV=py38-django30
      - python: 3.8
        env: TOX_ENV=py38-django31
      - python: 3.8
        env: TOX_ENV=py38-django32
      - python: 3.9
        env: TOX_ENV=py38-django31
      - python: 3.9
        env: TOX_ENV=py38-django32

script: tox -e $TOX_ENV

install:
    - pip install pip setuptools wheel -U
    - pip install tox tox-travis
